### ISSUE TITLE
Seems, that you cannot add a Medical Device category

### ISSUE THREAD

**Issue by glpimedicuser** [delcroip/glpi_open_medis#22]
Perhaps, I did not find the category I wanted (vision tester) but in fact it seems that I cannot add a category for medical devices.
Correct me if I made a mistake.

Br.

**Comment by delcroip** [comment]
Hi,

I had issue too, I rework the cat in the rc4, normally the updates works but you may have to unsintall the module and install it again (all openmedis data will be lost)

Also this version used the CND as medical cat

**Comment by glpimedicuser** [comment]
Is it possible to keep my data when I update my openmedis version ? Because I registered a lot of medical devices and that would be unfortunate to lose them. Maybe not for the moment but maybe soon ?

**Comment by delcroip** [comment]
Yes, I can make a specific script for you, can you make a dump of you data (I need the SQL table structure, because I did a lot of change since the first version and the update script were not correct)

Br

Patrick Delcroix
+41 79 618 69 78
***@***.***
________________________________
De : glpimedicuser ***@***.***>
Envoyé : mardi 13 juillet 2021 14:24
À : delcroip/gpli_plugin_openmedis
Cc: Patrick Delcroix; Comment 
Objet : Re: [delcroip/gpli_plugin_openmedis] Seems, that you cannot add a Medical Device category (#22)

Is it possible to keep my data when I update my openmedis version ? Because I registered a lot of medical devices and that would be unfortunate to lose them.

**Comment by glpimedicuser** [comment]
What do you mean by a dump of my data ? Would you want all tables of glpi's database, or just the tables for your plugin ? And how can I make you this dump because my server is on a command line system ?

Thank for your help,

Br

**Comment by delcroip** [comment]
Hello.

I don't need the data, this command should do the trick

mysqldump -u root -pmypassword mydb --no-data > mydump.sql

(You can do just -p instead of -pmypassword and after you press enter it will ask the MySQL user password -> mypassword  in the example above)

Do that after installing the new version and applying the update (click on the "+" in the plugin list , it won't remove any data, only the "-" is deleting all plugin data)


Br

**Comment by glpimedicuser** [comment]
So if I understand correctly. I must install the 1.0.1.rc4 version, than do your command in my cmdl (who make a dump of my data) and after that, applying the update by the "+" in the plugin list. And I won't lose my data with that.

Br

**Comment by delcroip** [comment]
almost:
1. you won't loose your data by clicking on the "+"
2. you will dump only the data structure (no data)

`mysqldump -u root -p mydb --no-data > myStructureDump.sql`

3. it is a good practice to do a full dump of the database before any update (plugins or GLPI) to have an insurance incase something goes wrong , it is the same command but without "--no-data" (please DON'T share this one)

`mysqldump -u root -p mydb  > myFullDump.sql`

the reason is that in rc2 and rc3 the migration scripts for the database had errors (table renaming, new fields ....) therefore were not always applied properly (it should be corrected now ).

So for your case, I need to see which migration was not done to make a custom script to apply them.

br

**Comment by glpimedicuser** [comment]
I just updated the plugin and as I can see without problems because all my data have been conserve. Thank for your help.

Br

**Comment by delcroip** [comment]
Good to hear,

Just check that the medical categories are working fine (most of the last changes were arround the categories).

Also, I don't know which nomenclature you are using, but the latest version use the European medical device nomenclature (EMDN , renaming of the italian CND) when the previous ones was closer the UMDNS 

br

**Comment by glpimedicuser** [comment]
Seems that all medical categories have been lose because I don't see them, on my GLPI, when I want to add one to a medical device. There is also two Medical device category (e.g. UMDS,GMDN). Is that a problem ? :
![same name in titles](https://user-images.githubusercontent.com/86647565/126275885-4822c78b-0c0b-4c4e-b9b9-4edabef61d1c.PNG)

There is also no categories in the two Medical device categories (e.g. UMDS,GMDN), still on GLPI :
![no categories in medical categories](https://user-images.githubusercontent.com/86647565/126275924-39891611-74a3-4e5b-95e9-6666275938f9.PNG)

But I have all categories on phpmyadmin :
![categories in phpmyadmin](https://user-images.githubusercontent.com/86647565/126277317-72092623-45d7-4e1f-8d79-a1897679147c.PNG)

I tried to create a medical category but even if I received the message saying that I created the category, I don't see it on GLPI, nor in phpmyadmin.

Br

**Comment by delcroip** [comment]
I can see from PHP admin that the full migration isn't done (I expected that) that is why the list is empty (SQL error because of missing column)

A screen shot of php Admin can be enough to make the script for that table (I need the column name with one or two line of data, I could guess the rest ).

Br

**Comment by glpimedicuser** [comment]
Is it enough ?
![image](https://user-images.githubusercontent.com/86647565/126305798-6597fe46-a283-43c9-9616-c2bb25de53e3.png)

Br

**Comment by delcroip** [comment]
Here is the code to update the table and then use this one to "populate" the complete name;
```
ALTER TABLE glpi_plugin_openmedis_medicaldevicecategories CHANGE name label  varchar(255)  DEFAULT '', ADD `name` text AS (CONCAT(code,' - ',label)), ADD `completename` text COLLATE utf8_unicode_ci;

UPDATE glpi_plugin_openmedis_medicaldevicecategories  SET completename = name WHERE level =1;

UPDATE glpi_plugin_openmedis_medicaldevicecategories 
JOIN (SELECT  id,completename  FROM glpi_plugin_openmedis_medicaldevicecategories) parent ON glpi_plugin_openmedis_medicaldevicecategories.plugin_openmedis_medicaldevicecategories_id = parent.id
SET glpi_plugin_openmedis_medicaldevicecategories.completename = CONCAT(parent.completename,'>',glpi_plugin_openmedis_medicaldevicecategories.name)  WHERE level =2;

UPDATE glpi_plugin_openmedis_medicaldevicecategories 
JOIN (SELECT  id,completename  FROM glpi_plugin_openmedis_medicaldevicecategories) parent ON glpi_plugin_openmedis_medicaldevicecategories.plugin_openmedis_medicaldevicecategories_id = parent.id
SET glpi_plugin_openmedis_medicaldevicecategories.completename = CONCAT(parent.completename,'>',glpi_plugin_openmedis_medicaldevicecategories.name)  WHERE level =3;
UPDATE glpi_plugin_openmedis_medicaldevicecategories 
JOIN (SELECT  id,completename  FROM glpi_plugin_openmedis_medicaldevicecategories) parent ON glpi_plugin_openmedis_medicaldevicecategories.plugin_openmedis_medicaldevicecategories_id = parent.id
SET glpi_plugin_openmedis_medicaldevicecategories.completename = CONCAT(parent.completename,'>',glpi_plugin_openmedis_medicaldevicecategories.name)  WHERE level =4;
UPDATE glpi_plugin_openmedis_medicaldevicecategories 
JOIN (SELECT  id,completename  FROM glpi_plugin_openmedis_medicaldevicecategories) parent ON glpi_plugin_openmedis_medicaldevicecategories.plugin_openmedis_medicaldevicecategories_id = parent.id
SET glpi_plugin_openmedis_medicaldevicecategories.completename = CONCAT(parent.completename,'>',glpi_plugin_openmedis_medicaldevicecategories.name)  WHERE level =5;
UPDATE glpi_plugin_openmedis_medicaldevicecategories 
JOIN (SELECT  id,completename  FROM glpi_plugin_openmedis_medicaldevicecategories) parent ON glpi_plugin_openmedis_medicaldevicecategories.plugin_openmedis_medicaldevicecategories_id = parent.id
SET glpi_plugin_openmedis_medicaldevicecategories.completename = CONCAT(parent.completename,'>',glpi_plugin_openmedis_medicaldevicecategories.name)  WHERE level =6;
```
